[package]
name = "bping"
version = "1.0.0"
authors = ["Firaenix <Nick.Carton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
clap = "2.33.1"
spinners = "1.2.0"
log = "0.4.8"
fern = "0.6.0"
toml = "0.5.6"
colored = "2.0"
tokio = { version = "0.2", features = ["full"] }
dirs = "3.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
futures = "0.3.5"
dialoguer = "0.6.2"
colorful = "0.2.1"
indicatif = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
celes = "1.0.5"
thiserror = "1.0.20"
async-stream = "0.3.0"
validator = { version = "0.11", feature = ["derive"] }
console = "0.12.0"