name: Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Tier 1 Platforms
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: bping
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: bping.exe
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: bping
          - target: i686-pc-windows-msvc
            os: windows-latest
            artifact_name: bping.exe
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: bping

          # Tier 2 Platforms
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: bping
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: bping
          - target: arm-unknown-linux-gnueabi
            os: ubuntu-latest
            artifact_name: bping
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            artifact_name: bping
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            artifact_name: bping

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
